//
//  react-native-inhouse-sdk-umbrella.h
//  react-native-inhouse-sdk
//
//  Generated by CocoaPods
//

#import <Foundation/Foundation.h>

#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#elif __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#import "RCTEventEmitter.h"
#endif

//! Project version number for react-native-inhouse-sdk.
FOUNDATION_EXPORT double react_native_inhouse_sdkVersionNumber;

//! Project version string for react-native-inhouse-sdk.
FOUNDATION_EXPORT const unsigned char react_native_inhouse_sdkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <react-native-inhouse-sdk/PublicHeader.h>

// Import your Objective-C bridge file
#import "TrackingSDKModule.h"

// Import Swift module - this will be generated by Xcode
#if __has_include("react-native-inhouse-sdk-Swift.h")
#import "react-native-inhouse-sdk-Swift.h"
#elif __has_include(<react-native-inhouse-sdk/react-native-inhouse-sdk-Swift.h>)
#import <react-native-inhouse-sdk/react-native-inhouse-sdk-Swift.h>
#endif

FOUNDATION_EXPORT double react_native_inhouse_sdkVersionNumber;
FOUNDATION_EXPORT const unsigned char react_native_inhouse_sdkVersionString[];